-- Generated by BladeSmith 4.00.TC1B2DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "opclass",
	"%SYSBLDUSER%", 0,
	"create opclass BoundingBox_ops for rtree
	strategies (Overlap, Equal, Contains, Within)
	support (Union, Size, Inter);
",
	"f",
	"drop opclass BoundingBox_ops restrict;
",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 7, "BoundingBox",
	"%SYSBLDUSER%", 0,
	"create opaque type BoundingBox(
	internallength = 48,
	alignment = 8
);

",
	"f",
	"drop type BoundingBox restrict;

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 71, "BoundingBox",
	"%SYSBLDUSER%", 0,
	"grant usage on type BoundingBox to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	71, "BoundingBox",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function BoundingBoxIn (lvarchar)
returns BoundingBox
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxInput)"" language c;

",
	"f",
	"drop function BoundingBoxIn (lvarchar);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxIn (lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxInput)"");

",
	"f",
	"alter function BoundingBoxIn (lvarchar)
	with (Modify External Name = ""BoundingBoxInput"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxIn (lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function BoundingBoxIn (lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxIn (lvarchar)
	with (add not variant);

",
	"f",
	"alter function BoundingBoxIn (lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BoundingBoxIn (lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "BoundingBoxIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "lvarchar->BoundingBox",
	"%SYSBLDUSER%", 0,
	"create implicit cast
	(
		lvarchar as BoundingBox
		with  BoundingBoxIn
	);

",
	"f",
	"drop cast (lvarchar as BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "lvarchar->BoundingBox",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function BoundingBoxOut (BoundingBox)
returns lvarchar
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxOutput)"" language c;

",
	"f",
	"drop function BoundingBoxOut (BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxOut (BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxOutput)"");

",
	"f",
	"alter function BoundingBoxOut (BoundingBox)
	with (Modify External Name = ""BoundingBoxOutput"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%",
	5, "BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxOut (BoundingBox)
	with (add parallelizable);

",
	"f",
	"alter function BoundingBoxOut (BoundingBox)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%",
	5, "BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxOut (BoundingBox)
	with (add not variant);

",
	"f",
	"alter function BoundingBoxOut (BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%",
	5, "BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BoundingBoxOut (BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%",
	5, "BoundingBoxOut (BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "BoundingBox->lvarchar",
	"%SYSBLDUSER%", 0,
	"create cast
	(
		BoundingBox as lvarchar
		with  BoundingBoxOut
	);

",
	"f",
	"drop cast (BoundingBox as lvarchar);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "BoundingBox->lvarchar",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BoundingBoxImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"create function BoundingBoxImpT (impexp)
returns BoundingBox
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxImportText)"" language c;

",
	"f",
	"drop function BoundingBoxImpT (impexp);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "BoundingBoxImpT (impexp)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BoundingBoxImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxImpT (impexp)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxImportText)"");

",
	"f",
	"alter function BoundingBoxImpT (impexp)
	with (Modify External Name = ""BoundingBoxImportText"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BoundingBoxImpT (impexp)",
	"%SYSBLDUSER%",
	5, "BoundingBoxImpT (impexp)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BoundingBoxImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BoundingBoxImpT (impexp) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "BoundingBoxImpT (impexp)",
	"%SYSBLDUSER%",
	5, "BoundingBoxImpT (impexp)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "impexp->BoundingBox",
	"%SYSBLDUSER%", 0,
	"create implicit cast
	(
		impexp as BoundingBox
		with  BoundingBoxImpT
	);

",
	"f",
	"drop cast (impexp as BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "impexp->BoundingBox",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BoundingBoxExpT (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function BoundingBoxExpT (BoundingBox)
returns impexp
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxExportText)"" language c;

",
	"f",
	"drop function BoundingBoxExpT (BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "BoundingBoxExpT (BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BoundingBoxExpT (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxExpT (BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxExportText)"");

",
	"f",
	"alter function BoundingBoxExpT (BoundingBox)
	with (Modify External Name = ""BoundingBoxExportText"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BoundingBoxExpT (BoundingBox)",
	"%SYSBLDUSER%",
	5, "BoundingBoxExpT (BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BoundingBoxExpT (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BoundingBoxExpT (BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "BoundingBoxExpT (BoundingBox)",
	"%SYSBLDUSER%",
	5, "BoundingBoxExpT (BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "BoundingBox->impexp",
	"%SYSBLDUSER%", 0,
	"create cast
	(
		BoundingBox as impexp
		with  BoundingBoxExpT
	);

",
	"f",
	"drop cast (BoundingBox as impexp);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "BoundingBox->impexp",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BoundingBoxImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"create function BoundingBoxImpB (impexpbin)
returns BoundingBox
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxImportBinary)"" language c;

",
	"f",
	"drop function BoundingBoxImpB (impexpbin);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "BoundingBoxImpB (impexpbin)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BoundingBoxImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxImpB (impexpbin)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxImportBinary)"");

",
	"f",
	"alter function BoundingBoxImpB (impexpbin)
	with (Modify External Name = ""BoundingBoxImportBinary"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BoundingBoxImpB (impexpbin)",
	"%SYSBLDUSER%",
	5, "BoundingBoxImpB (impexpbin)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BoundingBoxImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BoundingBoxImpB (impexpbin) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "BoundingBoxImpB (impexpbin)",
	"%SYSBLDUSER%",
	5, "BoundingBoxImpB (impexpbin)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "impexpbin->BoundingBox",
	"%SYSBLDUSER%", 0,
	"create implicit cast
	(
		impexpbin as BoundingBox
		with  BoundingBoxImpB
	);

",
	"f",
	"drop cast (impexpbin as BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "impexpbin->BoundingBox",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BoundingBoxExpB (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function BoundingBoxExpB (BoundingBox)
returns impexpbin
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxExportBinary)"" language c;

",
	"f",
	"drop function BoundingBoxExpB (BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "BoundingBoxExpB (BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BoundingBoxExpB (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxExpB (BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxExportBinary)"");

",
	"f",
	"alter function BoundingBoxExpB (BoundingBox)
	with (Modify External Name = ""BoundingBoxExportBinary"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BoundingBoxExpB (BoundingBox)",
	"%SYSBLDUSER%",
	5, "BoundingBoxExpB (BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BoundingBoxExpB (BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BoundingBoxExpB (BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "BoundingBoxExpB (BoundingBox)",
	"%SYSBLDUSER%",
	5, "BoundingBoxExpB (BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "BoundingBox->impexpbin",
	"%SYSBLDUSER%", 0,
	"create cast
	(
		BoundingBox as impexpbin
		with  BoundingBoxExpB
	);

",
	"f",
	"drop cast (BoundingBox as impexpbin);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "BoundingBox->impexpbin",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function Compare (BoundingBox,BoundingBox)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxCompare)"" language c;

",
	"f",
	"drop function Compare (BoundingBox,BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Compare (BoundingBox,BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxCompare)"");

",
	"f",
	"alter function Compare (BoundingBox,BoundingBox)
	with (Modify External Name = ""BoundingBoxCompare"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Compare (BoundingBox,BoundingBox)
	with (add parallelizable);

",
	"f",
	"alter function Compare (BoundingBox,BoundingBox)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Compare (BoundingBox,BoundingBox)
	with (add not variant);

",
	"f",
	"alter function Compare (BoundingBox,BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Compare (BoundingBox,BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Compare (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function Equal (BoundingBox,BoundingBox)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxEqual)"" language c;

",
	"f",
	"drop function Equal (BoundingBox,BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Equal (BoundingBox,BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxEqual)"");

",
	"f",
	"alter function Equal (BoundingBox,BoundingBox)
	with (Modify External Name = ""BoundingBoxEqual"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Equal (BoundingBox,BoundingBox)
	with (add parallelizable);

",
	"f",
	"alter function Equal (BoundingBox,BoundingBox)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Equal (BoundingBox,BoundingBox)
	with (add not variant);

",
	"f",
	"alter function Equal (BoundingBox,BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Equal (BoundingBox,BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Equal (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function NotEqual (BoundingBox,BoundingBox)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxNotEqual)"" language c;

",
	"f",
	"drop function NotEqual (BoundingBox,BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function NotEqual (BoundingBox,BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxNotEqual)"");

",
	"f",
	"alter function NotEqual (BoundingBox,BoundingBox)
	with (Modify External Name = ""BoundingBoxNotEqual"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function NotEqual (BoundingBox,BoundingBox)
	with (add parallelizable);

",
	"f",
	"alter function NotEqual (BoundingBox,BoundingBox)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function NotEqual (BoundingBox,BoundingBox)
	with (add not variant);

",
	"f",
	"alter function NotEqual (BoundingBox,BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function NotEqual (BoundingBox,BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "NotEqual (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function Contains (BoundingBox,BoundingBox)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxContains)"" language c;

",
	"f",
	"drop function Contains (BoundingBox,BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Contains (BoundingBox,BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxContains)"");

",
	"f",
	"alter function Contains (BoundingBox,BoundingBox)
	with (Modify External Name = ""BoundingBoxContains"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Contains (BoundingBox,BoundingBox)
	with (add parallelizable);

",
	"f",
	"alter function Contains (BoundingBox,BoundingBox)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Contains (BoundingBox,BoundingBox)
	with (add not variant);

",
	"f",
	"alter function Contains (BoundingBox,BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Contains (BoundingBox,BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Contains (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function Within (BoundingBox,BoundingBox)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxWithin)"" language c;

",
	"f",
	"drop function Within (BoundingBox,BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Within (BoundingBox,BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxWithin)"");

",
	"f",
	"alter function Within (BoundingBox,BoundingBox)
	with (Modify External Name = ""BoundingBoxWithin"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Within (BoundingBox,BoundingBox)
	with (add parallelizable);

",
	"f",
	"alter function Within (BoundingBox,BoundingBox)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Within (BoundingBox,BoundingBox)
	with (add not variant);

",
	"f",
	"alter function Within (BoundingBox,BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Within (BoundingBox,BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Within (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function Union (BoundingBox,BoundingBox,BoundingBox)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxUnion)"" language c;

",
	"f",
	"drop function Union (BoundingBox,BoundingBox,BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Union (BoundingBox,BoundingBox,BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxUnion)"");

",
	"f",
	"alter function Union (BoundingBox,BoundingBox,BoundingBox)
	with (Modify External Name = ""BoundingBoxUnion"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Union (BoundingBox,BoundingBox,BoundingBox)
	with (add parallelizable);

",
	"f",
	"alter function Union (BoundingBox,BoundingBox,BoundingBox)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Union (BoundingBox,BoundingBox,BoundingBox)
	with (add not variant);

",
	"f",
	"alter function Union (BoundingBox,BoundingBox,BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Union (BoundingBox,BoundingBox,BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Union (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Size (BoundingBox,double precision)",
	"%SYSBLDUSER%", 0,
	"create function Size (BoundingBox,double precision)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxSize)"" language c;

",
	"f",
	"drop function Size (BoundingBox,double precision);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Size (BoundingBox,double precision)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Size (BoundingBox,double precision)",
	"%SYSBLDUSER%", 0,
	"alter function Size (BoundingBox,double precision)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxSize)"");

",
	"f",
	"alter function Size (BoundingBox,double precision)
	with (Modify External Name = ""BoundingBoxSize"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Size (BoundingBox,double precision)",
	"%SYSBLDUSER%",
	5, "Size (BoundingBox,double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Size (BoundingBox,double precision)",
	"%SYSBLDUSER%", 0,
	"alter function Size (BoundingBox,double precision)
	with (add parallelizable);

",
	"f",
	"alter function Size (BoundingBox,double precision)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Size (BoundingBox,double precision)",
	"%SYSBLDUSER%",
	5, "Size (BoundingBox,double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Size (BoundingBox,double precision)",
	"%SYSBLDUSER%", 0,
	"alter function Size (BoundingBox,double precision)
	with (add not variant);

",
	"f",
	"alter function Size (BoundingBox,double precision)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Size (BoundingBox,double precision)",
	"%SYSBLDUSER%",
	5, "Size (BoundingBox,double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Size (BoundingBox,double precision)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Size (BoundingBox,double precision) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Size (BoundingBox,double precision)",
	"%SYSBLDUSER%",
	5, "Size (BoundingBox,double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function Inter (BoundingBox,BoundingBox,BoundingBox)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxInter)"" language c;

",
	"f",
	"drop function Inter (BoundingBox,BoundingBox,BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Inter (BoundingBox,BoundingBox,BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxInter)"");

",
	"f",
	"alter function Inter (BoundingBox,BoundingBox,BoundingBox)
	with (Modify External Name = ""BoundingBoxInter"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Inter (BoundingBox,BoundingBox,BoundingBox)
	with (add not variant);

",
	"f",
	"alter function Inter (BoundingBox,BoundingBox,BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Inter (BoundingBox,BoundingBox,BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Inter (BoundingBox,BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"create function Overlap (BoundingBox,BoundingBox)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxOverlap)"" language c;

",
	"f",
	"drop function Overlap (BoundingBox,BoundingBox);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	7, "BoundingBox",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Overlap (BoundingBox,BoundingBox)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxOverlap)"");

",
	"f",
	"alter function Overlap (BoundingBox,BoundingBox)
	with (Modify External Name = ""BoundingBoxOverlap"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Overlap (BoundingBox,BoundingBox)
	with (add parallelizable);

",
	"f",
	"alter function Overlap (BoundingBox,BoundingBox)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"alter function Overlap (BoundingBox,BoundingBox)
	with (add not variant);

",
	"f",
	"alter function Overlap (BoundingBox,BoundingBox)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Overlap (BoundingBox,BoundingBox) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%",
	5, "Overlap (BoundingBox,BoundingBox)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BoundingBoxVersion ()",
	"%SYSBLDUSER%", 0,
	"create function BoundingBoxVersion ()
returns lvarchar
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxVersion)"" language c;

",
	"f",
	"drop function BoundingBoxVersion ();

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BoundingBoxVersion ()",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxVersion ()
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/boundingbox.bld(BoundingBoxVersion)"");

",
	"f",
	"alter function BoundingBoxVersion ()
	with (Modify External Name = ""BoundingBoxVersion"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BoundingBoxVersion ()",
	"%SYSBLDUSER%",
	5, "BoundingBoxVersion ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-BoundingBoxVersion ()",
	"%SYSBLDUSER%", 0,
	"alter function BoundingBoxVersion ()
	with (add not variant);

",
	"f",
	"alter function BoundingBoxVersion ()
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-BoundingBoxVersion ()",
	"%SYSBLDUSER%",
	5, "BoundingBoxVersion ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BoundingBoxVersion ()",
	"%SYSBLDUSER%", 0,
	"grant execute on function BoundingBoxVersion () to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "BoundingBoxVersion ()",
	"%SYSBLDUSER%",
	5, "BoundingBoxVersion ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 15, "ifxrltree1",
	"%SYSBLDUSER%", 0,
	"insert into sysbldirequired
	(bldi_id, bld_id)
values
(
	""ifxrltree1"",
	""%SYSBLDNAME%""
);

",
	"f",
	"delete from sysbldirequired
	where bldi_id = ""ifxrltree1""
	and bld_id = ""%SYSBLDNAME%"";

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "sysbldregistered",
	"%SYSBLDUSER%", 0,
	"insert into sysbldregistered
	(bld_id)
values
(
	""%SYSBLDNAME%""
);

",
	"f",
	"delete from sysbldregistered
	where bld_id = ""%SYSBLDNAME%"";

",
	"f"
);

