-- Generated by BladeSmith 4.00.TC1B2DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysblddescription
	(bld_id, blocale_id, bdesc_format, bvendor_id, bdesc_desc, bdesc_copyright)
values
(
	"%SYSBLDNAME%",
	"en_us.8859-1",
	0,
	"INFORMIX",
	"R-Tree indexable range type with operators Overlap, Contains, Within.",
	"Copyright (c) 1981-99 Informix Software, Inc.  All rights reserved."
);

delete from sysbldvendors
	where bvendor_id = "INFORMIX" and
	bvendor_format = 0 and
	blocale_id = "en_us.8859-1";

insert into sysbldvendors
	(bvendor_id, bvendor_name, blocale_id, bvendor_format, bvendor_desc)
values
(
	"INFORMIX",
	"Informix Software, Inc.",
	"en_us.8859-1",
	0,
	"Informix Software, Inc.
4100 Bohannon Drive
Menlo Park, CA  94025"
);

